-- use of Cast and Convert Functions

-- CAST FUNCTIONS

SELECT CAST('Hello World' AS VARCHAR);

SELECT CAST('123.4853' AS DECIMAL(5,1));

SELECT CAST('122.453' AS DECIMAL(4,1));

SELECT CAST(122.453 AS INT);

SELECT CAST('122.45213111313' AS FLOAT);

SELECT CAST('SQL' AS INT) AS RESULT

SELECT CAST(NULL as INT) AS RESULT

SELECT CAST('NULL' as VARCHAR) AS RESULT

DECLARE @MyVar SQL_VARIANT;
SET @MyVar = CAST('hello' AS CHAR(2));
SELECT @MyVar
SELECT SQL_VARIANT_PROPERTY(@MyVar, 'BaseType') AS DataType;
	


-- CONVERT FUNCTIONS

SELECT CONVERT(VARCHAR,1234);

SELECT CONVERT(DECIMAL(10,2),'11232.123');

SELECT CONVERT(NVARCHAR,N'😎');

SELECT CONVERT (VARCHAR,GETDATE(),103);

SELECT CONVERT (VARCHAR,GETDATE(),101);

SELECT CONVERT(VARCHAR(250),'This is a really long piece of string') AS TestString

SELECT LEN(CONVERT(VARCHAR,'This is a really long piece of string')) AS TestString

SELECT CAST('This is a really long piece of string' as VARCHAR(250))

SELECT CAST('This is a really long piece of string' as VARCHAR)

SELECT CONVERT(VARCHAR(20), GETDATE(), 107) AS FormattedDate;

SELECT CAST('2025-04-01' AS DATE) AS ConvertedDate; 

SELECT CAST('2025-4-1' AS DATE) AS ConvertedDate; 

SELECT MONTH(CAST('02-04-2025' AS DATE)) AS ConvertedDate; 

-- PARSE

SELECT PARSE('€345,98' AS money USING 'de-DE') AS Result; ​

SELECT PARSE('$1,000.75' AS MONEY USING 'en-US') AS US_Currency;

SELECT PARSE('123456.78' AS FLOAT) AS Result;



SELECT '1' + 1 AS ImplicitConversion,
       CAST(1 AS VARCHAR) + '1' AS ExplicitConversion;

SELECT SQL_VARIANT_PROPERTY('1' + 1, 'BaseType') AS DataType;
SELECT SQL_VARIANT_PROPERTY(CAST(1 as VARCHAR)+'1', 'BaseType')  AS DataType;


SELECT CAST('00123' AS INT) AS CastResult;

SELECT CONVERT(INT, '000123.') AS ConvertResult;

SELECT PARSE('001221'AS INT) as RESULT


-- TRY functions
SELECT CONVERT(INT,'SQL') AS RESULT
seleCT CONVERT(int,NULL) AS RESULT

SELECT TRY_CONVERT(INT, 'ABC') AS SafeConversion;
SELECT TRY_CAST('ABC' as INT) AS SAFEConversion;
SELECT TRY_PARSE('ABC' as INT) AS SafeConversion;