SELECT LEN('Hello world');

SELECT LOWER('HELLO WORLD');

SELECT UPPER('hello world');

SELECT LTRIM('   SQL');

SELECT RTRIM('   SQL     ');
SELECT LEN(RTRIM('   SQL     '));

SELECT SUBSTRING('this is SQL',9,3)

SELECT REPLACE('This is SQL','t','o')

SELECT CHARINDEX('i','This is SQL');


SELECT GETDATE();

SELECT DATEPART(WEEKDAY,getDAte());

SELECT TRANSLATE('monday','day',replicate(' ',3));

SELECT MONTH(GETDATE());

SELECT DAY(GETDATE());

SELECT CURRENT_TIMESTAMP

SELECT RIGHT('HELLO',2);


